#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# Load utility methods
. "$ROOT_DIR/utils"

if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then

    info "check if configuration exists"
    location=$(cli_call rc location)
    if [ ! -f "$location" ];
    then
        warning "Missing '$location' file"
        cli_call rc init
        exit 1
    fi

    info "check if configuration information are readable"
    while read -r site;
    do
        configexists=$(jq -r --arg site "$site" '.sites[$site].config' "$location")
        if [ "$configexists" == "null" ]; then
            newconfig=$(jq -r --arg site "$site" '.sites[$site].config={}' "$location")
            echo "$newconfig" > "$location"
        fi
    done < <(jq -r '.sites | to_entries[] | .key' "$location" | sed '/^$/d')
fi
