#!/usr/bin/env bash

RC_PATH="$HOME/.$(cat "$ROOT_DIR"/app/.name)rc.json"

if [[ -f "$RC_PATH" ]]; then
    >&2 echo -e "\033[31m'$RC_PATH' already exists\033[39m"
    >&2 echo "We'd rather not overwrite runtime configuration file you've already created."
    exit 1
fi

cat > "$RC_PATH" <<EOF
{
    "root_folder": "~/sources",
    "config": {
        "user.name": "Your Name"
        "user.email": "youremail@yourprovider.tld"
    },
    "sites": {
        "github.yourentreprise.com/EntrepriseOrganization": {
            "site": "github.yourentreprise.com",
            "api": "https://github.yourentreprise.com/api/v3",
            "owner": "EntrepriseOrganization",
            "type": "orgs",
            "token": "YOUR API TOKEN from github.yourentreprise.com"
            "config": {
                "user.name": "Your Name In Your Entreprise"
                "user.email": "youremail@yourentreprise.com"
            },
        },
        "github.com/YOUR_LOGIN": {
            "site": "github.com",
            "api": "https://api.github.com",
            "owner": "YOUR_LOGIN",
            "type": "users",
            "token": "YOUR API TOKEN from github.com",
            "config": {}
        }
    }
}
EOF

echo "You can now edit your runtime configuration file: $RC_PATH"
